server:
  port: 8401

spring:
  application:
    name: springcloud-alibaba-sentinel-service


  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.186:8848
    sentinel:
      transport:
        dashboard: 192.168.1.186:8080
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: "*"
