server:
  port: 9002

spring:
  application:
    name: springcloud-payment-provider-service


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"