server:
  port: 8002
spring:
  application:
    name: springcloud-payment-service-8002
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.159/springcloud_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root-xz
  cloud:
    zookeeper:
      connect-string: 192.168.1.159:2181


mybatis:
  config-location: classpath:/mybatis/mybatis.cfg.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.tingyu.springcloud.entities
debug: true

